# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v4
      with:
        repositories: '[{ "id": "eventstreams-schemas-repository", "url": "https://eventstreams-cp4i-ibm-es-rest-route-eventstreams-cp4i.gse-eda-demo-202005-fa9ee67c9ab6a7791435450358e564cc-0000.us-south.containers.appdomain.cloud/files/schemas" }]'
        servers: '[{ "id": "eventstreams-schemas-repository", "configuration": {"httpHeaders": {"property": {"name": "Authorization", "value": "Bearer $EVENT_STREAMS_SECRET"}}} }]'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
